### ISSUE TITLE
命名規則によるVM抽出

### ISSUE THREAD

**Issue by miwa-sys** [PythonGakusyu/repository#1]

**Comment by miwa-sys** [comment]
ブランチ名はfeature-prob9でお願いします。

**Comment by MT-rensyu** [comment]
kadai9.pyをpushしましたのでレビューよろしくお願いいたします。
kadai6.pyはkadai9.pyで用いたメソッドのモジュールになります。
![9](https://user-images.githubusercontent.com/39143932/39909652-aac178d0-552e-11e8-8204-12dd0f0ab89e.png)

**Comment by miwa-sys** [comment]
問題の修正なのですが
OS名を表示→VM名を表示
でお願い致します。

ソース拝見致しました。
こちらも問題の不備が原因なのですが、
"他のOSも同様の命名規則で存在する"という前提で考慮してください。
(この場合、centosである事を区別できるよう修正をお願い致します。)

**Comment by MT-rensyu** [comment]
ご指摘いただきありがとうございます。
修正し、再度push致しましたのでご確認のほどよろしくお願いします。
![9](https://user-images.githubusercontent.com/39143932/39910327-b578887e-5531-11e8-835e-afe32444f171.png)

**Comment by miwa-sys** [comment]
正規表現が適切でない為再度修正をお願い致します。

**Comment by MT-rensyu** [comment]
ご指摘いただきありがとうございます。
再度修正し、push致しましたのでご確認のほどよろしくお願いします。
![9](https://user-images.githubusercontent.com/39143932/39912274-299f41a0-5539-11e8-91f9-6bfa1dcd0887.png)

**Comment by miwa-sys** [comment]
'^centos...g1$'  の場合
もしも番号が2桁だった場合に対応できない為
識別番号として"数字がある事"を意識した正規表現へ修正をお願い致します。

**Comment by MT-rensyu** [comment]
ご指摘いただきありがとうございます。
再度修正し、push致しましたのでご確認のほどよろしくお願いします。

![](https://user-images.githubusercontent.com/39143932/39912274-299f41a0-5539-11e8-91f9-6bfa1dcd0887.png)

**Comment by miwa-sys** [comment]
確認致しました。
適切な修正がされていると思います。大丈夫です。
ご対応ありがとうございます。お疲れ様でした。
