### ISSUE TITLE
ホストにアクセスしhostname取得(paramiko)

### ISSUE THREAD

**Issue by miwa-sys** [PythonGakusyu/repository#5]

**Comment by MT-rensyu** [comment]
お疲れ様です。
遅くなってしまい申し訳ございません。
kadai13.pyをブランチfearture-getParamikoにプッシュしましたので
ご確認よろしくお願い致します
![13](https://user-images.githubusercontent.com/39143932/40773883-20b24864-64ff-11e8-84d9-2d0763fd15e7.png)
。

**Comment by MT-rensyu** [comment]
お疲れ様です。kadai13.pyを修正し、fearture-getParamikoにプッシュしましたので
ご確認よろしくお願い致します。
![default](https://user-images.githubusercontent.com/39143932/40895866-b94a57a2-67ec-11e8-9672-a2dcce277bbd.png)

**Comment by MT-rensyu** [comment]
お疲れ様です。kadai13.pyのメソッドの切り分け、ssh接続時の例外処理の追加、出力の修正を行いfearture-getParamikoにプッシュしましたので、ご確認よろしくお願い致します。
![13](https://user-images.githubusercontent.com/39143932/40905656-95d4c942-6819-11e8-99be-b35a015782b3.png)
